development:
  adapter: mysql
  database: bible_dev
  host: 127.0.0.1
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: bible_test
  host: 127.0.0.1
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: bible
  host: 127.0.0.1
  username: root
  password: root
  pool: 5
  timeout: 5000